# Generated by Django 4.2.24 on 2025-09-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensemodel',
            name='category',
            field=models.CharField(choices=[('F', 'FOOD'), ('T', 'TRAVEL'), ('E', 'ENTERTAINMENT'), ('S', 'SPORTS'), ('O', 'OTHERS')], max_length=2),
        ),
    ]
