# Generated by Django 4.2.24 on 2025-09-25 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0002_alter_expensemodel_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpenseModel',
        ),
    ]
